Imports System

Namespace Facebook
	Public NotInheritable Partial Class GraphApi
        Partial Public NotInheritable Class Account
            Public NotInheritable Class Fields
                Private Sub New()
                End Sub
                Public Const About As String = "about"
                Public Const AccessToken As String = "access_token"
                Public Const Affiliation As String = "affiliation"
                Public Const AppID As String = "app_id"
                Public Const ArtistsWeLike As String = "artists_we_like"
                Public Const Attire As String = "attire"
                Public Const Awards As String = "awards"
                Public Const BandInterests As String = "band_interests"
                Public Const BandMembers As String = "band_members"
                Public Const Bio As String = "bio"
                Public Const Birthday As String = "birthday"
                Public Const BookingAgent As String = "booking_agent"
                Public Const BudgetRecources As String = "budget_recs"
                Public Const CanPost As String = "can_post"
                Public Const Built As String = "built"
                Public Const Category As String = "category"
                Public Const CategoryList As String = "category_list"
                Public Const Checkins As String = "checkins"
                Public Const CompanyOverview As String = "company_overview"
                Public Const Cover As String = "cover"
                Public Const CulinaryTeam As String = "culinary_team"
                Public Const CurrentLocation As String = "current_location"
                Public Const Description As String = "description"
                Public Const DescriptionHtml As String = "description_html"
                Public Const DirectedBy As String = "directed_by"
                Public Const Features As String = "features"
                Public Const FoodStyles As String = "food_styles"
                Public Const Founded As String = "founded"
                Public Const GeneralInfo As String = "general_info"
                Public Const GeneralManager As String = "general_manager"
                Public Const Genre As String = "genre"
                Public Const GlobalBrandPageName As String = "global_brand_page_name"
                Public Const GlobalBrandParentPage As String = "global_brand_parent_page"
                Public Const HasAddedApp As String = "has_added_app"
                Public Const Hometown As String = "hometown"
                Public Const Hours As String = "hours"
                Public Const ID As String = "id"
                Public Const Influences As String = "influences"
                Public Const IsCommunityPage As String = "is_community_page"
                Public Const IsPublished As String = "is_published"
                Public Const Keywords As String = "keywords"
                Public Const Likes As String = "likes"
                Public Const Link As String = "link"
                Public Const Location As String = "location"
                Public Const Members As String = "members"
                Public Const Mission As String = "mission"
                Public Const Mpg As String = "mpg"
                Public Const Name As String = "name"
                Public Const Network As String = "network"
                Public Const NewLikeCount As String = "new_like_count"
                Public Const OfferEligible As String = "offer_eligible"
                Public Const ParentPage As String = "parent_page"
                Public Const Parking As String = "parking"
                Public Const PaymentOptions As String = "payment_options"
                Public Const Permissions As String = "perms"
                Public Const PersonalInfo As String = "personal_info"
                Public Const PersonalInterests As String = "personal_interests"
                Public Const PharmaseuticalSafetyInfo As String = "pharma_safety_info"
                Public Const Phone As String = "phone"
                Public Const PlotOutlint As String = "plot_outline"
                Public Const PressContact As String = "press_contact"
                Public Const PriceRange As String = "price_range"
                Public Const ProducedBy As String = "produced_by"
                Public Const Products As String = "products"
                Public Const PromotionEligible As String = "promotion_eligible"
                Public Const PromotionIneligibleReason As String = "promotion_ineligible_reason"
                Public Const PublicTransit As String = "public_transit"
                Public Const RecordLabel As String = "record_label"
                Public Const ReleaseDate As String = "release_date"
                Public Const RestaurantServices As String = "restaurant_services"
                Public Const RestaurantSpecialties As String = "restaurant_specialties"
                Public Const Schedule As String = "schedule"
                Public Const ScreenplayBy As String = "screenplay_by"
                Public Const Season As String = "season"
                Public Const Starring As String = "starring"
                Public Const Studio As String = "studio"
                Public Const TalkingAboutCount As String = "talking_about_count"
                Public Const UnreadMessageCount As String = "unread_message_count"
                Public Const UnreadNotificationCount As String = "unread_notif_count"
                Public Const UnseenMessageCount As String = "unseen_message_count"
                Public Const Username As String = "username"
                Public Const Website As String = "website"
                Public Const WereHereCount As String = "were_here_count"
                Public Const WrittenBy As String = "written_by"
            End Class
        End Class
	End Class
End Namespace
